### PR TITLE
Make improvements to GPIO

### PR DESCRIPTION
**Pull request by hannobraun**
I've requested review from @jscarrott, since he said he he wanted to work on GPIO this weekend, but of course everyone else is also welcome to review/merge this. I'd appreciate a close look at the open-drain commit, as I might have misunderstood something there.

@jscarrott, I'm sorry for making the GPIO code more complicated before you wanted to look into refactoring it. If this turns out to be a problem, feel free to disregard this for now. I'm happy to rebase this pull request later on top of your work.

### CODE REVIEW

**Comment by hannobraun** [comment]
Forgot to update the board code again. Fixed and rebased.

**Comment by jscarrott** [comment]
Looks fine to me. Just has a conflict, I'll probably base my refactor on this code. Which I'll hopefully have a chance to start this evening.

**Comment by hannobraun** [comment]
Rebased on master.

**Comment by hannobraun** [comment]
Merging, since @jscarrott already said it looked fine, and I fixed the conflict.

**Pull request merged**
