### PR TITLE
Add nRF9160 to README, and use new name for PAC crate.

### PR DESCRIPTION
**Pull request by thejpster**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Looks like more crates need to be updated to the new PAC. Other than that this looks good!

**Comment by thejpster** [comment]
It's worse - some of the peripherals have been renamed. And the 
nrf9160-pac didn't build on docs.rs because .cargo/config specifies a 
target they don't have.

I'll do a 0.2.1 of the PAC without the default target set. No-one should 
be building the PAC by itself anyway, as it's a library not a binary. 
Then I'll work out what peripherals have changed.

**Comment by thejpster** [comment]
Looks likes this got fixed up in e7940e3e!

**Comment by thejpster** [comment]
Ping @jonas-schievink

**Pull request merged**
