### PR TITLE
Interrupted uart example missing from #102

### PR DESCRIPTION
**Pull request by jacobrosenthal**
This can pulled against #102 or rebased on top of that, whatever. 

I grabbed his example I found https://github.com/korken89/rtfm_workshop/blob/newhal/examples/pool.rs

and just made the necessary changes to get it to compile with current master

Its mainly waiting on cortex-m-rtfm update to 0.5.0

Compiles, but no promises on working yet, Im still playing with it.

Also this may not be the best place for the example to go, I could see it going under one of the board examples as it hardcodes pins, but I think those dont play well with rtfm right now?

cc @korken89

### CODE REVIEW

**Comment by korken89** [comment]
Hi, I gave it a try but I am getting the error:

```
error[E0277]: the trait bound `nrf52_hal_common::uarte::DMAPool: heapless::pool::singleton::Pool` is not satisfied
  --> src/main.rs:93:27
   |
93 |         static mut TX_RB: Option<Queue<Box<DMAPool>, TXQSize>> = None;
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `heapless::pool::singleton::Pool` is not implemented for `nrf52_hal_common::uarte::DMAPool`
   |
   = note: required by `heapless::pool::singleton::Box`
```

Not sure what is causing it though...

**Comment by jacobrosenthal** [comment]
Hrm. Oh, I didnt include my .cargo for the example Maybe thats it? Pushing

Otherwise
```
$ cd nrf52-hal/examples/rtfm-uarte-interrupts
$ rustc --version
rustc 1.36.0 (a53f9df32 2019-07-03)
$ cargo clean
$ cargo build
..
    Finished dev [unoptimized + debuginfo] target(s) in 1m 56s
$
```

**Comment by korken89** [comment]
Seems all fine, not sure what went wrong when I tried it :)

**Comment by korken89** [comment]
I will try and merge this with the existing PR, if that is ok with you?

**Comment by jacobrosenthal** [comment]
Absolutely

**Comment by korken89** [comment]
Hey man, sorry for the delay - I went on vacation :)
I'm going to merge this together today/tomorrow so you know!

**Comment by korken89** [comment]
This is now part of the other PR :)

**Pull request closed without merging**
